import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useEffect, useRef, useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function HomeScreen() {
  const contactUsSectionRef = useRef<HTMLElement | null>(null);
  // Function to scroll to the Contact Us section
  const scrollToContactUs = () => {
    if (contactUsSectionRef.current) {
      contactUsSectionRef.current.scrollIntoView({ behavior: "smooth" });
    }
  };
  const letsGoSectionRef = useRef<HTMLElement | null>(null);
  // Function to scroll to the Contact Us section
  const scrollToLetsGo = () => {
    if (letsGoSectionRef.current) {
      letsGoSectionRef.current.scrollIntoView({ behavior: "smooth" });
    }
  };

  const [isShowen, setIsShowen] = useState(true);

  useEffect(() => {
    let prevScrollPos = typeof window !== "undefined" ? window.pageYOffset : 0;

    const handleScroll = () => {
      const currentScrollPos =
        typeof window !== "undefined" ? window.pageYOffset : 0;
      if (prevScrollPos > currentScrollPos) {
        setIsShowen(true);
      } else {
        setIsShowen(false);
      }
      prevScrollPos = currentScrollPos;
    };

    if (typeof window !== "undefined") {
      window.addEventListener("scroll", handleScroll);
    }

    return () => {
      if (typeof window !== "undefined") {
        window.removeEventListener("scroll", handleScroll);
      }
    };
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.mainHome}>Home</div>
    </>
  );
}
