import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Navbar from "@/components/navbar/Navbar";
import Header from "@/components/header/Header";
import Body from "@/components/body/Body";
import Contect from "@/components/contacts/Contect";
import Footer from "@/components/footer/Footer";
import { useEffect, useRef, useState } from "react";
import Ourclients from "@/components/ourclients/Ourclients";

const inter = Inter({ subsets: ["latin"] });

export default function About() {
  const contactUsSectionRef = useRef<HTMLElement | null>(null);
  // Function to scroll to the Contact Us section
  const scrollToContactUs = () => {
    if (contactUsSectionRef.current) {
      contactUsSectionRef.current.scrollIntoView({ behavior: "smooth" });
    }
  };
  const letsGoSectionRef = useRef<HTMLElement | null>(null);
  // Function to scroll to the Contact Us section
  const scrollToLetsGo = () => {
    if (letsGoSectionRef.current) {
      letsGoSectionRef.current.scrollIntoView({ behavior: "smooth" });
    }
  };

  const [isShowen, setIsShowen] = useState(true);

  useEffect(() => {
    let prevScrollPos = window.pageYOffset;

    const handleScroll = () => {
      const currentScrollPos = window.pageYOffset;
      if (prevScrollPos > currentScrollPos) {
        setIsShowen(true);
      } else {
        setIsShowen(false);
      }
      prevScrollPos = currentScrollPos;
    };

    window.addEventListener("scroll", handleScroll);

    return () => {
      window.removeEventListener("scroll", handleScroll);
    };
  }, []);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
}
